/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121437-gf4a87d8ca4-20251015"
#endif /* AVUTIL_FFVERSION_H */
